### ISSUE TITLE
Need guide for transformation from old prometheus queries (3.4.0) to new queries (4.0.0)

### ISSUE THREAD

**Issue by MilesBehind** [ahus1/prometheus-hystrix#20]
I wanted to use an existing grafana dashboard (https://grafana.com/dashboards/2113) that nicely shows hystrix circuit breaker information. It didn't work at all. It took me hours to find the reason: the grafana dashboard uses metrics that are to exported anymore as of version 4.0.0 of prometheus-hystrix.
It would be nice to include a transformation guide for the metrics. 
An additional question: why did you change the exported metrics in the first place? I do not understand the benefits of the complete metric rewrite.

**Comment by ahus1** [comment]
Although the Grafana dashboard has been build for an earlier version of this library, it is not affiliated with the project. Maybe @sergiu-svinarciuc can comment here if he plans to update the dashboard or is willing to accept help for updating it. 

If you pick the last 3.x version of the library you will find that it includes both the old and the new metrics.

To find out what changed in the different versions please have [a look at the changelog](https://github.com/ahus1/prometheus-hystrix/blob/master/CHANGELOG.md).

The reason to change the metrics is twofold: 

* The original metrics were a 1:1 representation of the internal Hystrix metrics. But they didn't follow [the conventions for Prometheus Metrics naming](https://prometheus.io/docs/practices/naming/).

* Instead of publishing rates and pre-calculated percentiles the new metrics export counters and histograms. These kinds of metrics can be aggregated over several nodes (for example a cluster) while the previous can't.
