### ISSUE TITLE
Graveyard this repo.

### ISSUE THREAD

**Issue by beorn7** [ahus1/prometheus-hystrix#7]
The maintained fork is now https://github.com/ahus1/prometheus-hystrix .

**Comment by grobie** [comment]
Instead of a fork, we could have just transferred the repo to the new maintainer, which would have kept HTTP redirects in place.

**Comment by ahus1** [comment]
we could still transfer the repo. But I haven't done that before... I assume I'll have to delete the fork first before you can transfer it. But this could be done...

**Comment by beorn7** [comment]
If that's possible out of the SoundCloud GH org, even better.

**Comment by grobie** [comment]
The prerequisites seem to be:

* The current fork needs to be deleted to free up the name.
* There is a Github restriction "You can only transfer a repository from an organization to yourself at this time". It's possible to transfer from a user to another user though, so we could do
  1) add you temporarily to the SoundCloud org so that you can transfer the repo to your own user account
  2) one of use first moves it to their personal account and then moves it again to you

@diurnalist

**Comment by ahus1** [comment]
@beorn7 / @grobie - I send you my phone number via email. We can talk this over this evening or tomorrow morning when needed.

**Comment by beorn7** [comment]
I kind of knew that wouldn't be easy...

I think ii. sounds way more feasible than i.

**Comment by grobie** [comment]
Alright, I moved the repo to my own account. @ahus1 let me know once you have freed up the prometheus-hystrix name in your account (by renaming/deleting the fork), and I'll transfer ownership.

**Comment by ahus1** [comment]
@grobie - fork has been deleted. ready to receive...

**Comment by grobie** [comment]
Sent. You'll need to accept and it'll be yours. Thanks and good luck.

**Comment by ahus1** [comment]
Touchdown!

**Comment by beorn7** [comment]
You are amazing folks!
